sequenceDiagram
actor User
participant Browser
participant Middleware
participant BookController
participant ReviewController
participant AppDbContext
autonumber

    User-)Browser: Click on book page link
    Browser-)Middleware: GET Book/Index
    Middleware-)BookController: GET Index()
    activate BookController
    BookController-)AppDbContext: GetAllBooks()
     activate AppDbContext
    AppDbContext-)BookController: books: List
    deactivate AppDbContext
    BookController-)Middleware: Index View books: List
    deactivate BookController
    Middleware-)Browser: Index: HTML
    Browser-->>User: Shows list of books

    User-)Browser: Click on book link
    Browser-)ReviewController: GET Index