sequenceDiagram
actor User
participant Browser
participant Index View
participant BookController
participant ReviewController
participant AppDbContext
autonumber

    User-)Browser: Click on book page link
    Browser-)BookController: GET /Book/Index
    BookController-)AppDbContext: GetAllBooks
    AppDbContext-)BookController: books: List
    BookController-)Index View: books: List
    Index View-)Browser: Book/Index page
    Browser-->>User: Shows list of books

    User-)Browser: Click on book link
    Browser-)ReviewController: GET /Review/